import { z } from 'zod';

export const ticketSchema = z.object({
  description: z.string().optional(),
  location: z.string().optional(),
  category: z.string().optional(),
  priority: z.string().optional(),
  targetDate: z.string().optional(),
  photoUrl: z.string().optional(),
  requestorName: z.string().optional(),
  ticketId: z.string().optional(),
  source: z.string().optional(),
  status: z.string().optional(),
  date: z.any().optional(),
  isUrgent: z.boolean().optional(),
  completionDate: z.any().optional(),
  repairAction: z.string().optional(),
  sparepartName: z.string().optional(),
  sparepartQty: z.number().optional(),
  notes: z.string().optional(),
  ttdUser: z.string().optional(),
  picName: z.string().optional(),
  pic_name: z.string().optional(),
  area: z.string().optional(),
  kategori: z.string().optional(),
  sumber: z.string().optional(),
  severity: z.string().optional(),
  deskripsi: z.string().optional()
}).passthrough();

export const workOrderSchema = z.object({
  equipmentName: z.string().optional(),
  issueDescription: z.string().optional(),
  requestorName: z.string().optional(),
  category: z.string().optional(),
  priority: z.string().optional(),
  woId: z.string().optional(),
  date: z.any().optional(),
  status: z.string().optional(),
  ttdUser: z.string().optional(),
  repairStart: z.any().optional(),
  repairEnd: z.any().optional(),
  requestorNik: z.string().optional(),
  equipmentCode: z.string().optional(),
  location: z.string().optional(),
  photoUrl: z.string().optional(),
  shift: z.string().optional(),
  devOptions: z.any().optional(),
}).passthrough();
