import React, { useState, useEffect, useMemo } from 'react';
import { motion } from 'motion/react';
import { 
  ClipboardList, ClipboardCheck, Camera, Users, Utensils, Shield, 
  FileText, MessageSquare, Trophy, Sparkles, ChevronRight, 
  CheckCircle2, Clock, AlertTriangle, ArrowRight, Settings2,
  ThermometerSun, Heart, RefreshCw, Smartphone, Eye, ShieldAlert,
  Wrench, PlusCircle, BarChart3
} from 'lucide-react';
import { toast } from 'sonner';
import { FoodReportModal } from './food-report-modal';
import { SimplifiedInspectionModal } from './SimplifiedInspectionModal';
import { SimplifiedP5mModal } from './SimplifiedP5mModal';
import QuotesPoolModal, { CommunityQuoteItem } from './QuotesPoolModal';
import { DevRoleplaySwitcher, getSimulatedProfile, SimulatedProfile } from './DevRoleplaySwitcher';
import { LeadershipDashboardModal } from './LeadershipDashboardModal';
import { getDailySkenaQuote, SkenaQuote } from '../utils/skena-quotes';
import { isPicTemuanRole, getOpenFindingsForSupervisor } from '../utils/inspection-pic-matcher';

interface MobileSimpleHomeScreenProps {
  inspectorName: string;
  inspectorNik: string;
  onNav: (tab: any) => void;
  userPt?: string;
  onSwitchToFullMode: () => void;
}

export function MobileSimpleHomeScreen({
  inspectorName,
  inspectorNik,
  onNav,
  userPt,
  onSwitchToFullMode
}: MobileSimpleHomeScreenProps) {
  const [showFoodModal, setShowFoodModal] = useState(false);
  const [showInspectionModal, setShowInspectionModal] = useState(false);
  const [showP5mModal, setShowP5mModal] = useState(false);
  const [inspectionDefaultTab, setInspectionDefaultTab] = useState<'weekly' | 'kta_tta' | 'findings' | 'p2h'>('weekly');
  const [openFindingsCount, setOpenFindingsCount] = useState<number>(0);
  const [profile, setProfile] = useState<any>(null);
  const [dailyTasks, setDailyTasks] = useState<any>(null);
  const [mySchedule, setMySchedule] = useState<any>(null);
  const [p5mAssignment, setP5mAssignment] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  // Dev Roleplay & Leadership state
  const [simProfile, setSimProfile] = useState<SimulatedProfile | null>(() => getSimulatedProfile());
  const [showLeadershipModal, setShowLeadershipModal] = useState(false);
  const [leadershipTargetRole, setLeadershipTargetRole] = useState<'spt_prep' | 'spt_lab' | 'manager'>('manager');

  useEffect(() => {
    const handleSimChange = (e: any) => {
      setSimProfile(e.detail || null);
    };
    window.addEventListener('dev-roleplay-changed', handleSimChange);
    return () => window.removeEventListener('dev-roleplay-changed', handleSimChange);
  }, []);

  // Quotes Pool & Modal State
  const [showQuotesPoolModal, setShowQuotesPoolModal] = useState(false);
  const [quotesModalTab, setQuotesModalTab] = useState<'details' | 'explore' | 'create'>('details');
  const [communityQuotesList, setCommunityQuotesList] = useState<CommunityQuoteItem[]>([]);
  const [selectedPoolQuote, setSelectedPoolQuote] = useState<CommunityQuoteItem | null>(null);

  // Quote of the day base fallback
  const [activeQuote, setActiveQuote] = useState<SkenaQuote>(() => {
    return getDailySkenaQuote(inspectorNik || inspectorName || 'user');
  });

  // Fetch Community Quotes
  useEffect(() => {
    fetch('/api/quotes')
      .then(res => res.json())
      .then(json => {
        if (json.status === 'success' && Array.isArray(json.data) && json.data.length > 0) {
          setCommunityQuotesList(json.data);
        }
      })
      .catch(() => {});
  }, []);

  // Compute active community quote item
  const activeCommunityQuote: CommunityQuoteItem = useMemo(() => {
    if (selectedPoolQuote) return selectedPoolQuote;

    if (communityQuotesList.length > 0) {
      const matched = communityQuotesList.find(q => q.quote === activeQuote.quote);
      if (matched) return matched;

      const dateStr = new Date().toISOString().split('T')[0];
      const seed = `${(inspectorNik || inspectorName || 'user').trim().toLowerCase()}_daily_quote_${dateStr}`;
      let hash = 0;
      for (let i = 0; i < seed.length; i++) {
        hash = ((hash << 5) - hash) + seed.charCodeAt(i);
        hash |= 0;
      }
      const idx = Math.abs(hash) % communityQuotesList.length;
      return communityQuotesList[idx];
    }

    return {
      id: 1,
      quote: activeQuote.quote,
      authorNik: '00000000000',
      authorName: 'Generated by AI',
      authorRole: 'AI Assistant',
      authorSection: 'Lab & Prep',
      category: activeQuote.tag || 'Motivasi & Skena',
      likesCount: 0,
      likedBy: [],
      likedByUsers: []
    };
  }, [selectedPoolQuote, communityQuotesList, activeQuote, inspectorNik, inspectorName]);

  useEffect(() => {
    try {
      const p = JSON.parse(localStorage.getItem('p2h_inspector_profile') || '{}');
      setProfile(p);
    } catch {
      // ignore
    }

    // Try reading cached daily tasks and schedules first
    try {
      const cachedDaily = localStorage.getItem('p2h_cached_daily_tasks');
      if (cachedDaily) setDailyTasks(JSON.parse(cachedDaily));

      const cachedSchedule = localStorage.getItem('p2h_cached_my_schedule');
      if (cachedSchedule) setMySchedule(JSON.parse(cachedSchedule));

      const cachedP5m = localStorage.getItem('p2h_cached_p5m_assignment');
      if (cachedP5m) setP5mAssignment(JSON.parse(cachedP5m));
    } catch {
      // ignore
    }

    // Safe JSON parser helper to prevent <!doctype HTML parse errors
    const safeJson = async (res: Response) => {
      try {
        if (!res.ok) return null;
        const ct = res.headers.get('content-type') || '';
        if (!ct.includes('application/json')) return null;
        return await res.json();
      } catch {
        return null;
      }
    };

    // Fetch live summary data with correct backend endpoints
    const fetchSummary = async () => {
      if (!inspectorNik && !inspectorName) {
        setLoading(false);
        return;
      }
      try {
        const queryParams = new URLSearchParams();
        if (inspectorNik) queryParams.set('nik', inspectorNik);
        if (inspectorName) queryParams.set('name', inspectorName);

        const [dailyRes, schedRes, p5mRes] = await Promise.allSettled([
          fetch(`/api/daily-tasks-status?${queryParams.toString()}`),
          fetch(`/api/inspection-schedule?${queryParams.toString()}`),
          fetch(`/api/p5m/schedules/user-assignment?${queryParams.toString()}&includePast=true`)
        ]);

        if (dailyRes.status === 'fulfilled') {
          const dJson = await safeJson(dailyRes.value);
          if (dJson && dJson.success) {
            setDailyTasks(dJson);
            try { localStorage.setItem('p2h_cached_daily_tasks', JSON.stringify(dJson)); } catch {}
          }
        }

        if (schedRes.status === 'fulfilled') {
          const sJson = await safeJson(schedRes.value);
          if (sJson && sJson.found && sJson.schedule) {
            setMySchedule(sJson.schedule);
            try { localStorage.setItem('p2h_cached_my_schedule', JSON.stringify(sJson.schedule)); } catch {}
          }
        }

        if (p5mRes.status === 'fulfilled') {
          const pJson = await safeJson(p5mRes.value);
          if (pJson && pJson.success && pJson.assignment) {
            setP5mAssignment(pJson.assignment);
            try { localStorage.setItem('p2h_cached_p5m_assignment', JSON.stringify(pJson.assignment)); } catch {}
          }
        }

        // Jika user adalah PIC (SPV / Specialist), hitung temuan terbuka di areanya
        const currentRole = profile?.jabatan || localStorage.getItem('p2h_inspector_jabatan') || '';
        if (isPicTemuanRole(currentRole)) {
          try {
            const tickRes = await fetch('/api/tickets');
            if (tickRes.ok) {
              const tickData = await safeJson(tickRes);
              if (Array.isArray(tickData)) {
                const matched = getOpenFindingsForSupervisor(currentRole, tickData);
                setOpenFindingsCount(matched.openFindings?.length || 0);
              }
            }
          } catch {}
        }
      } catch (err) {
        console.warn('Error fetching simple mode data:', err);
      } finally {
        setLoading(false);
      }
    };

    fetchSummary();
  }, [inspectorNik, inspectorName]);

  // Greeting calculation
  const hour = new Date().getHours();
  const greetingText = 
    hour >= 4 && hour < 11 ? 'Selamat Pagi' :
    hour >= 11 && hour < 15 ? 'Selamat Siang' :
    hour >= 15 && hour < 18 ? 'Selamat Sore' : 'Selamat Malam';

  // Effective roleplay values
  const effectiveName = simProfile?.name || inspectorName || 'Personil PrepLab';
  const effectiveRole = simProfile?.role || profile?.jabatan || localStorage.getItem('p2h_inspector_jabatan') || 'Crew Operasional';
  const effectiveSection = simProfile?.section || profile?.section || 'Preparasi & Lab';
  const effectiveNik = simProfile?.nik || inspectorNik;

  const secLower = effectiveSection.toLowerCase();
  const roleLower = effectiveRole.toLowerCase();

  const isSuperAdmin = 
    inspectorNik === '02D25000055' || 
    inspectorNik === '02D24000043' || 
    inspectorNik === '04D21001047' || 
    inspectorNik === '04D24000042' ||
    inspectorNik === 'preplabadmin';

  const isDeveloper = isSuperAdmin || localStorage.getItem('p2h_is_developer') === 'true';

  // Section & Role flags
  const isManager = roleLower.includes('manager') || roleLower.includes('head') || roleLower.includes('ktt');
  const isSpt = roleLower.includes('superintendent') || roleLower.includes('spt');
  const isSptPrep = isSpt && secLower.includes('prep');
  const isSptLab = isSpt && secLower.includes('lab');
  const hasLeadershipDashboard = isManager || isSptPrep || isSptLab;

  const isAdministrasi = secLower.includes('admin') || secLower.includes('administrasi') || secLower.includes('hr');
  const isMaintenance = secLower.includes('maint') || secLower.includes('pemeliharaan');
  const isInventoryControl = secLower.includes('inventory') || secLower.includes('inv') || roleLower.includes('inventory');
  const isLaboratory = secLower.includes('lab') && !isInventoryControl;
  const isPreparation = secLower.includes('prep') || secLower.includes('preparasi');
  const isPic = isPicTemuanRole(effectiveRole);

  // Status checks
  const p2hDone = !!(dailyTasks?.p2h?.completedToday);
  const pemantauanDone = !!(dailyTasks?.pemantauan?.completedToday);
  const weeklyInspectionDone = !!(mySchedule?.isCompleted);

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      transition={{ duration: 0.25 }}
      className="w-full pb-28 px-3.5 space-y-4 max-w-lg mx-auto"
    >
      {/* ── DEV ROLEPLAY SWITCHER (DEV/ADMIN ONLY) ── */}
      {isDeveloper && (
        <DevRoleplaySwitcher onProfileChange={(sim) => setSimProfile(sim)} />
      )}
      {/* ── TOP HERO PROFILE CARD (SIMPLE & FOCUSED) ── */}
      <div 
        className="relative overflow-hidden rounded-3xl p-4 sm:p-5 border shadow-sm"
        style={{
          backgroundColor: 'var(--card-bg, #FFFFFF)',
          borderColor: 'var(--border-main, #E2E8F0)'
        }}
      >
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-3">
            {/* Avatar Profile */}
            <div 
              className="w-12 h-12 rounded-2xl flex items-center justify-center font-display font-black text-lg shadow-inner border border-teal-500/20 shrink-0 text-white"
              style={{
                background: 'linear-gradient(135deg, var(--primary, #0D9488) 0%, #059669 100%)'
              }}
            >
              {profile?.avatar ? (
                <img src={profile.avatar} alt={inspectorName} className="w-full h-full object-cover rounded-2xl" />
              ) : (
                <span>{inspectorName ? inspectorName.charAt(0).toUpperCase() : 'P'}</span>
              )}
            </div>

            {/* Name & Role */}
            <div className="min-w-0">
              <span className="text-[11px] font-bold text-[var(--text-muted)] block leading-none mb-1">
                {greetingText},
              </span>
              <h2 className="text-base font-black text-[var(--text-main)] font-display truncate leading-tight">
                {effectiveName}
              </h2>
              <div className="flex items-center gap-1.5 mt-0.5 flex-wrap">
                <span className="text-[10px] font-semibold text-[var(--text-muted)] truncate">
                  {effectiveRole}
                </span>
                <span className="text-[9px] font-bold px-1.5 py-0.2 rounded-md bg-teal-500/15 text-teal-700 dark:text-teal-300 border border-teal-500/25">
                  {effectiveSection}
                </span>
                <span className="text-[9px] font-bold px-1.5 py-0.2 rounded-md bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border border-emerald-500/25">
                  ● Onsite
                </span>
              </div>
            </div>
          </div>

          {/* Mode Switch Pill Button */}
          <button
            type="button"
            onClick={onSwitchToFullMode}
            className="flex items-center gap-1 px-2.5 py-1 rounded-full bg-teal-500/10 hover:bg-teal-500/20 text-teal-700 dark:text-teal-300 border border-teal-500/25 text-[10px] font-bold shrink-0 transition-all active:scale-95 shadow-2xs"
            title="Klik untuk beralih ke Mode Lengkap"
          >
            <Smartphone className="w-3 h-3 text-teal-600 dark:text-teal-400" />
            <span>Mode Sederhana</span>
          </button>
        </div>

        {/* Compact Daily Motivational Quote Ticker */}
        {activeCommunityQuote && (
          <div 
            onClick={() => {
              setQuotesModalTab('details');
              setShowQuotesPoolModal(true);
            }}
            className="mt-3.5 pt-2.5 border-t border-[var(--border-main)]/60 flex items-center justify-between gap-2 text-xs cursor-pointer group hover:bg-amber-500/5 -mx-1 px-1 rounded-lg transition-colors"
            title="Buka Detail & Kumpulan Quotes Komunitas"
          >
            <div className="flex items-center gap-1.5 min-w-0">
              <Sparkles className="w-3.5 h-3.5 text-amber-500 shrink-0" />
              <p className="text-[11px] italic text-[var(--text-muted)] truncate group-hover:text-[var(--text-main)] transition-colors">
                "{activeCommunityQuote.quote}"
              </p>
            </div>
            <span className="text-[10px] text-amber-600 dark:text-amber-400 font-bold shrink-0 flex items-center">
              Quote <ChevronRight className="w-3 h-3 inline" />
            </span>
          </div>
        )}
      </div>

      {/* ── EXECUTIVE / LEADERSHIP DASHBOARD TRIGGER CARD (SPT UP) ── */}
      {hasLeadershipDashboard && (
        <button
          type="button"
          onClick={() => {
            if (isManager) setLeadershipTargetRole('manager');
            else if (isSptPrep) setLeadershipTargetRole('spt_prep');
            else setLeadershipTargetRole('spt_lab');
            setShowLeadershipModal(true);
          }}
          className="w-full p-3.5 rounded-2xl border text-left flex items-center justify-between gap-3 shadow-xs hover:shadow-md active:scale-98 transition-all cursor-pointer overflow-hidden relative group"
          style={{
            backgroundColor: 'var(--card-bg, #FFFFFF)',
            borderColor: isManager ? 'rgba(245, 158, 11, 0.4)' : isSptPrep ? 'rgba(16, 185, 129, 0.4)' : 'rgba(168, 85, 247, 0.4)'
          }}
        >
          <div className="flex items-center gap-3 min-w-0">
            <div className={`w-10 h-10 rounded-xl flex items-center justify-center border shrink-0 ${
              isManager 
                ? 'bg-amber-500/15 text-amber-600 border-amber-500/30' 
                : isSptPrep 
                  ? 'bg-emerald-500/15 text-emerald-600 border-emerald-500/30' 
                  : 'bg-purple-500/15 text-purple-600 border-purple-500/30'
            }`}>
              <BarChart3 className="w-5 h-5" />
            </div>
            <div className="min-w-0">
              <div className="flex items-center gap-1.5">
                <span className={`text-[9.5px] font-black uppercase tracking-wider px-1.5 py-0.2 rounded-md border ${
                  isManager 
                    ? 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/25' 
                    : isSptPrep 
                      ? 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/25' 
                      : 'bg-purple-500/15 text-purple-700 dark:text-purple-300 border-purple-500/25'
                }`}>
                  Executive Panel
                </span>
                <span className="text-[10px] text-[var(--text-muted)]">● Realtime Sync</span>
              </div>
              <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-amber-600 transition-colors leading-tight mt-0.5 truncate">
                {isManager ? 'Executive Dashboard PrepLab' : isSptPrep ? 'Dashboard SPT Preparation' : 'Dashboard SPT Laboratory'}
              </h4>
              <p className="text-[10px] text-[var(--text-muted)] truncate">
                {isManager ? 'Tinjauan keselamatan, kesiapan alat, & manpower' : isSptPrep ? 'Kesiapan armada alat berat & kepatuhan P2H kru' : 'Integritas suhu/gas, instrumen lab, & analis'}
              </p>
            </div>
          </div>
          <div className="w-8 h-8 rounded-xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center shrink-0 group-hover:translate-x-0.5 transition-transform">
            <ChevronRight className="w-4 h-4 text-[var(--text-muted)] group-hover:text-[var(--text-main)]" />
          </div>
        </button>
      )}

      {/* ── SECTION: 4 TUGAS UTAMA (ADAPTIF SESUAI SEKSI) ── */}
      <div className="space-y-2">
        <div className="flex items-center justify-between px-1">
          <h3 className="text-xs font-black uppercase tracking-wider text-[var(--text-muted)] flex items-center gap-1.5">
            <ClipboardList className="w-3.5 h-3.5 text-teal-600" />
            <span>Aksi Cepat Tugas Hari Ini</span>
          </h3>
          <span className="text-[10px] font-bold text-teal-600 dark:text-teal-400">
            {effectiveSection}
          </span>
        </div>

        <div className="grid grid-cols-2 gap-2.5">
          {/* ═══════════════════════════════════════════
              KONDISI 1: SECTION ADMINISTRASI & HR
             ═══════════════════════════════════════════ */}
          {isAdministrasi ? (
            <>
              {/* 1. UPDATE ROSTER HARIAN */}
              <button
                type="button"
                onClick={() => onNav('roster-admin')}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'rgba(99, 102, 241, 0.4)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center border shrink-0 bg-indigo-500/10 text-indigo-600 border-indigo-500/25">
                    <Clock className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full border bg-indigo-500/15 text-indigo-700 dark:text-indigo-300 border-indigo-500/30">
                    Administrasi
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-indigo-600 transition-colors leading-tight">
                    Update Roster Harian
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    Kelola status shift &amp; cuti kerja
                  </p>
                </div>
              </button>

              {/* 2. SAP MANAGEMENT MINGGUAN */}
              <button
                type="button"
                onClick={() => onNav('sap-dashboard')}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'rgba(168, 85, 247, 0.4)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center border shrink-0 bg-purple-500/10 text-purple-600 border-purple-500/25">
                    <FileText className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full border bg-purple-500/15 text-purple-700 dark:text-purple-300 border-purple-500/30">
                    Mingguan
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-purple-600 transition-colors leading-tight">
                    SAP Management
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    Sinkronisasi &amp; notifikasi SAP
                  </p>
                </div>
              </button>

              {/* 3. INSPEKSI, KTA & TTA */}
              <button
                type="button"
                onClick={() => {
                  setInspectionDefaultTab('weekly');
                  setShowInspectionModal(true);
                }}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: weeklyInspectionDone ? 'rgba(16, 185, 129, 0.4)' : 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className={`w-9 h-9 rounded-xl flex items-center justify-center border shrink-0 ${
                    weeklyInspectionDone
                      ? 'bg-emerald-500/15 text-emerald-600 border-emerald-500/30'
                      : 'bg-amber-500/10 text-amber-600 border-amber-500/25'
                  }`}>
                    <ClipboardCheck className="w-5 h-5" />
                  </div>
                  <span className={`text-[9.5px] font-bold px-2 py-0.5 rounded-full border ${
                    weeklyInspectionDone
                      ? 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30'
                      : 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30'
                  }`}>
                    {weeklyInspectionDone ? '✓ Sudah Diisi' : 'Inspeksi & K3L'}
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-amber-600 transition-colors leading-tight">
                    Inspeksi, KTA &amp; TTA
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    {weeklyInspectionDone ? '✓ Lihat Bukti Screenshot' : 'Inspeksi rutin & lapor K3L'}
                  </p>
                </div>
              </button>

              {/* 4. BUAT WORK ORDER PERMINTAAN */}
              <button
                type="button"
                onClick={() => onNav('create-wo')}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl bg-orange-500/10 text-orange-600 border border-orange-500/25 flex items-center justify-center shrink-0">
                    <PlusCircle className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full bg-orange-500/15 text-orange-700 dark:text-orange-300 border border-orange-500/30">
                    Request / WO
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-orange-600 transition-colors leading-tight">
                    Buat Work Order (WO)
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    Pengajuan sarana / perbaikan
                  </p>
                </div>
              </button>
            </>
          ) : isMaintenance ? (
            /* ═══════════════════════════════════════════
               KONDISI 2: SECTION MAINTENANCE
               ═══════════════════════════════════════════ */
            <>
              {/* 1. MONITORING & SELESAIKAN WO */}
              <button
                type="button"
                onClick={() => onNav('wo-list')}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'rgba(245, 158, 11, 0.4)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center border shrink-0 bg-amber-500/10 text-amber-600 border-amber-500/25">
                    <Wrench className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full border bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30">
                    Maintenance
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-amber-600 transition-colors leading-tight">
                    Monitoring &amp; Selesaikan WO
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    Daftar WO &amp; closing perbaikan
                  </p>
                </div>
              </button>

              {/* 2. BUAT WORK ORDER MAINTENANCE */}
              <button
                type="button"
                onClick={() => onNav('create-wo')}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl bg-orange-500/10 text-orange-600 border border-orange-500/25 flex items-center justify-center shrink-0">
                    <PlusCircle className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full bg-orange-500/15 text-orange-700 dark:text-orange-300 border border-orange-500/30">
                    WO Internal
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-orange-600 transition-colors leading-tight">
                    Buat WO Baru
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    Form overhaul &amp; preventive
                  </p>
                </div>
              </button>

              {/* 3. INSPEKSI, KTA & TTA */}
              <button
                type="button"
                onClick={() => {
                  setInspectionDefaultTab('weekly');
                  setShowInspectionModal(true);
                }}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: weeklyInspectionDone ? 'rgba(16, 185, 129, 0.4)' : 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className={`w-9 h-9 rounded-xl flex items-center justify-center border shrink-0 ${
                    weeklyInspectionDone
                      ? 'bg-emerald-500/15 text-emerald-600 border-emerald-500/30'
                      : 'bg-amber-500/10 text-amber-600 border-amber-500/25'
                  }`}>
                    <ClipboardCheck className="w-5 h-5" />
                  </div>
                  <span className={`text-[9.5px] font-bold px-2 py-0.5 rounded-full border ${
                    weeklyInspectionDone
                      ? 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30'
                      : 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30'
                  }`}>
                    {weeklyInspectionDone ? '✓ Sudah Diisi' : 'Inspeksi & K3L'}
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-amber-600 transition-colors leading-tight">
                    Inspeksi, KTA &amp; TTA
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    {weeklyInspectionDone ? '✓ Lihat Bukti Screenshot' : 'Inspeksi rutin & lapor K3L'}
                  </p>
                </div>
              </button>

              {/* 4. BRIEFING P5M */}
              <button
                type="button"
                onClick={() => setShowP5mModal(true)}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl bg-purple-500/10 text-purple-600 border border-purple-500/25 flex items-center justify-center shrink-0">
                    <Users className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full bg-purple-500/15 text-purple-700 dark:text-purple-300 border border-purple-500/30">
                    Briefing
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-purple-600 transition-colors leading-tight">
                    Briefing P5M
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    {p5mAssignment?.materi || p5mAssignment?.topicTitle || 'Pertemuan 5 menit'}
                  </p>
                </div>
              </button>
            </>
          ) : isLaboratory ? (
            /* ═══════════════════════════════════════════
               KONDISI 3: SECTION LABORATORY
               ═══════════════════════════════════════════ */
            <>
              {/* 1. PEMANTAUAN HARIAN LAB */}
              <button
                type="button"
                onClick={() => onNav('pemantauan')}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: pemantauanDone ? 'rgba(16, 185, 129, 0.4)' : 'rgba(14, 165, 233, 0.4)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center border shrink-0 bg-sky-500/10 text-sky-600 border-sky-500/25">
                    <ThermometerSun className="w-5 h-5" />
                  </div>
                  <span className={`text-[9.5px] font-bold px-2 py-0.5 rounded-full border ${
                    pemantauanDone 
                      ? 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30' 
                      : 'bg-sky-500/15 text-sky-700 dark:text-sky-300 border-sky-500/30'
                  }`}>
                    {pemantauanDone ? '✓ Sudah Input' : 'Wajib Tiap Hari'}
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-sky-600 transition-colors leading-tight">
                    Pemantauan Lab
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    Suhu, kelembaban &amp; gas detector
                  </p>
                </div>
              </button>

              {/* 2. INSPEKSI HARIAN (P2H) INSTRUMEN LAB */}
              <button
                type="button"
                onClick={() => onNav('inspect')}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: p2hDone ? 'rgba(16, 185, 129, 0.4)' : 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className={`w-9 h-9 rounded-xl flex items-center justify-center border shrink-0 ${
                    p2hDone 
                      ? 'bg-emerald-500/15 text-emerald-600 border-emerald-500/30' 
                      : 'bg-teal-500/10 text-teal-600 border-teal-500/25'
                  }`}>
                    <ClipboardList className="w-5 h-5" />
                  </div>
                  <span className={`text-[9.5px] font-bold px-2 py-0.5 rounded-full border ${
                    p2hDone 
                      ? 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30' 
                      : 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30'
                  }`}>
                    {p2hDone ? '✓ Sudah Diisi' : 'Instrumen Lab'}
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-teal-600 transition-colors leading-tight">
                    P2H Instrumen Lab
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    XRF, timbangan, &amp; furnace
                  </p>
                </div>
              </button>

              {/* 3. BRIEFING P5M */}
              <button
                type="button"
                onClick={() => setShowP5mModal(true)}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl bg-purple-500/10 text-purple-600 border border-purple-500/25 flex items-center justify-center shrink-0">
                    <Users className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full bg-purple-500/15 text-purple-700 dark:text-purple-300 border border-purple-500/30">
                    Briefing
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-purple-600 transition-colors leading-tight">
                    Briefing P5M
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    {p5mAssignment?.materi || p5mAssignment?.topicTitle || 'Pertemuan 5 menit'}
                  </p>
                </div>
              </button>

              {/* 4. INSPEKSI, KTA & TTA */}
              <button
                type="button"
                onClick={() => {
                  setInspectionDefaultTab('weekly');
                  setShowInspectionModal(true);
                }}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: weeklyInspectionDone ? 'rgba(16, 185, 129, 0.4)' : 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className={`w-9 h-9 rounded-xl flex items-center justify-center border shrink-0 ${
                    weeklyInspectionDone
                      ? 'bg-emerald-500/15 text-emerald-600 border-emerald-500/30'
                      : 'bg-amber-500/10 text-amber-600 border-amber-500/25'
                  }`}>
                    <ClipboardCheck className="w-5 h-5" />
                  </div>
                  <span className={`text-[9.5px] font-bold px-2 py-0.5 rounded-full border ${
                    weeklyInspectionDone
                      ? 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30'
                      : 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30'
                  }`}>
                    {weeklyInspectionDone ? '✓ Sudah Diisi' : 'Inspeksi & K3L'}
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-amber-600 transition-colors leading-tight">
                    Inspeksi, KTA &amp; TTA
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    {weeklyInspectionDone ? '✓ Lihat Bukti Screenshot' : 'Inspeksi rutin & lapor K3L'}
                  </p>
                </div>
              </button>

              {/* 5. BUAT WORK ORDER (WO) */}
              <button
                type="button"
                onClick={() => onNav('create-wo')}
                className="col-span-2 sm:col-span-1 group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl bg-orange-500/10 text-orange-600 border border-orange-500/25 flex items-center justify-center shrink-0">
                    <Wrench className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full bg-orange-500/15 text-orange-700 dark:text-orange-300 border border-orange-500/30">
                    Lapor Alat
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-orange-600 transition-colors leading-tight">
                    Buat Work Order (WO)
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    Lapor alat rusak ke Maintenance
                  </p>
                </div>
              </button>
            </>
          ) : isInventoryControl ? (
            /* ═══════════════════════════════════════════
               KONDISI 4: SECTION INVENTORY CONTROL
               ═══════════════════════════════════════════ */
            <>
              {/* 1. INVENTORY CONTROL APD & DOKUMEN */}
              <button
                type="button"
                onClick={() => onNav('inventory')}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'rgba(245, 158, 11, 0.4)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center border shrink-0 bg-amber-500/10 text-amber-600 border-amber-500/25">
                    <Shield className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full border bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30">
                    Inventory
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-amber-600 transition-colors leading-tight">
                    Inventory Control (APD)
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    Distribusi APD &amp; stok barang
                  </p>
                </div>
              </button>

              {/* 2. BRIEFING P5M */}
              <button
                type="button"
                onClick={() => setShowP5mModal(true)}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl bg-purple-500/10 text-purple-600 border border-purple-500/25 flex items-center justify-center shrink-0">
                    <Users className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full bg-purple-500/15 text-purple-700 dark:text-purple-300 border border-purple-500/30">
                    Briefing
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-purple-600 transition-colors leading-tight">
                    Briefing P5M
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    {p5mAssignment?.materi || p5mAssignment?.topicTitle || 'Pertemuan 5 menit'}
                  </p>
                </div>
              </button>

              {/* 3. INSPEKSI, KTA & TTA */}
              <button
                type="button"
                onClick={() => {
                  setInspectionDefaultTab('weekly');
                  setShowInspectionModal(true);
                }}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: weeklyInspectionDone ? 'rgba(16, 185, 129, 0.4)' : 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className={`w-9 h-9 rounded-xl flex items-center justify-center border shrink-0 ${
                    weeklyInspectionDone
                      ? 'bg-emerald-500/15 text-emerald-600 border-emerald-500/30'
                      : 'bg-amber-500/10 text-amber-600 border-amber-500/25'
                  }`}>
                    <ClipboardCheck className="w-5 h-5" />
                  </div>
                  <span className={`text-[9.5px] font-bold px-2 py-0.5 rounded-full border ${
                    weeklyInspectionDone
                      ? 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30'
                      : 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30'
                  }`}>
                    {weeklyInspectionDone ? '✓ Sudah Diisi' : 'Inspeksi & K3L'}
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-amber-600 transition-colors leading-tight">
                    Inspeksi, KTA &amp; TTA
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    {weeklyInspectionDone ? '✓ Lihat Bukti Screenshot' : 'Inspeksi rutin & lapor K3L'}
                  </p>
                </div>
              </button>

              {/* 4. BUAT WORK ORDER (WO) */}
              <button
                type="button"
                onClick={() => onNav('create-wo')}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl bg-orange-500/10 text-orange-600 border border-orange-500/25 flex items-center justify-center shrink-0">
                    <PlusCircle className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full bg-orange-500/15 text-orange-700 dark:text-orange-300 border border-orange-500/30">
                    Request / WO
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-orange-600 transition-colors leading-tight">
                    Buat Work Order (WO)
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    Pengajuan sarana / perbaikan
                  </p>
                </div>
              </button>
            </>
          ) : (
            /* ═══════════════════════════════════════════
               KONDISI 4: SECTION PREPARATION (DEFAULT)
               ═══════════════════════════════════════════ */
            <>
              {/* 1. INSPEKSI HARIAN (P2H) */}
              <button
                type="button"
                onClick={() => onNav('inspect')}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: p2hDone ? 'rgba(16, 185, 129, 0.4)' : 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className={`w-9 h-9 rounded-xl flex items-center justify-center border shrink-0 ${
                    p2hDone 
                      ? 'bg-emerald-500/15 text-emerald-600 border-emerald-500/30' 
                      : 'bg-teal-500/10 text-teal-600 border-teal-500/25'
                  }`}>
                    <ClipboardList className="w-5 h-5" />
                  </div>
                  <span className={`text-[9.5px] font-bold px-2 py-0.5 rounded-full border ${
                    p2hDone 
                      ? 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30' 
                      : 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30'
                  }`}>
                    {p2hDone ? '✓ Sudah Diisi' : '⏳ Belum Diisi'}
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-teal-600 transition-colors leading-tight">
                    Inspeksi Harian (P2H)
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    Peralatan preparasi pra-operasi
                  </p>
                </div>
              </button>

              {/* 2. INSPEKSI, KTA & TTA */}
              <button
                type="button"
                onClick={() => {
                  setInspectionDefaultTab('weekly');
                  setShowInspectionModal(true);
                }}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: weeklyInspectionDone ? 'rgba(16, 185, 129, 0.4)' : 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className={`w-9 h-9 rounded-xl flex items-center justify-center border shrink-0 ${
                    weeklyInspectionDone
                      ? 'bg-emerald-500/15 text-emerald-600 border-emerald-500/30'
                      : 'bg-amber-500/10 text-amber-600 border-amber-500/25'
                  }`}>
                    <ClipboardCheck className="w-5 h-5" />
                  </div>
                  <span className={`text-[9.5px] font-bold px-2 py-0.5 rounded-full border ${
                    weeklyInspectionDone
                      ? 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30'
                      : 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30'
                  }`}>
                    {weeklyInspectionDone ? '✓ Sudah Diisi' : 'Inspeksi & K3L'}
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-amber-600 transition-colors leading-tight">
                    Inspeksi, KTA &amp; TTA
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    {weeklyInspectionDone ? '✓ Lihat Bukti Screenshot' : 'Inspeksi rutin & lapor K3L'}
                  </p>
                </div>
              </button>

              {/* 3. BRIEFING P5M */}
              <button
                type="button"
                onClick={() => setShowP5mModal(true)}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl bg-purple-500/10 text-purple-600 border border-purple-500/25 flex items-center justify-center shrink-0">
                    <Users className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full bg-purple-500/15 text-purple-700 dark:text-purple-300 border border-purple-500/30">
                    Briefing
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-purple-600 transition-colors leading-tight">
                    Briefing P5M
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    {p5mAssignment?.materi || p5mAssignment?.topicTitle || 'Pertemuan 5 menit'}
                  </p>
                </div>
              </button>

              {/* 4. BUAT WORK ORDER (WO) */}
              <button
                type="button"
                onClick={() => onNav('create-wo')}
                className="group relative flex flex-col justify-between p-3.5 rounded-2xl border text-left transition-all active:scale-95 shadow-xs hover:shadow-md cursor-pointer overflow-hidden min-h-[120px]"
                style={{
                  backgroundColor: 'var(--card-bg, #FFFFFF)',
                  borderColor: 'var(--border-main, #E2E8F0)'
                }}
              >
                <div className="flex items-center justify-between w-full">
                  <div className="w-9 h-9 rounded-xl bg-orange-500/10 text-orange-600 border border-orange-500/25 flex items-center justify-center shrink-0">
                    <Wrench className="w-5 h-5" />
                  </div>
                  <span className="text-[9.5px] font-bold px-2 py-0.5 rounded-full bg-orange-500/15 text-orange-700 dark:text-orange-300 border border-orange-500/30">
                    Lapor Alat
                  </span>
                </div>
                <div className="mt-2">
                  <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-orange-600 transition-colors leading-tight">
                    Buat Work Order (WO)
                  </h4>
                  <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
                    Lapor kerusakan alat ke Maintenance
                  </p>
                </div>
              </button>
            </>
          )}
        </div>
      </div>

      {/* ── SECTION KHUSUS PIC TEMUAN (SPV & SPECIALIST) ── */}
      {isPic && (
        <button
          type="button"
          onClick={() => {
            setInspectionDefaultTab('findings');
            setShowInspectionModal(true);
          }}
          className="w-full p-3.5 rounded-2xl border text-left flex items-center justify-between gap-3 shadow-xs hover:shadow-md active:scale-98 transition-all cursor-pointer overflow-hidden relative group"
          style={{
            backgroundColor: 'var(--card-bg, #FFFFFF)',
            borderColor: openFindingsCount > 0 ? 'rgba(239, 68, 68, 0.4)' : 'var(--border-main, #E2E8F0)'
          }}
        >
          <div className="flex items-center gap-3 min-w-0">
            <div className={`w-10 h-10 rounded-2xl flex items-center justify-center shrink-0 border ${
              openFindingsCount > 0 
                ? 'bg-rose-500/15 text-rose-600 border-rose-500/30' 
                : 'bg-emerald-500/15 text-emerald-600 border-emerald-500/30'
            }`}>
              <ShieldAlert className="w-5 h-5" />
            </div>
            <div className="min-w-0">
              <div className="flex items-center gap-1.5 flex-wrap">
                <h4 className="font-bold text-xs sm:text-sm text-[var(--text-main)] group-hover:text-rose-600 transition-colors">
                  Manajemen Temuan Inspeksi
                </h4>
                <span className="text-[9px] font-black px-1.5 py-0.2 rounded-md bg-rose-500/15 text-rose-700 dark:text-rose-300 border border-rose-500/25 uppercase">
                  PIC Area
                </span>
              </div>
              <p className="text-[10.5px] text-[var(--text-muted)] truncate mt-0.5">
                {openFindingsCount > 0 
                  ? `${openFindingsCount} temuan inspeksi perlu tindakan & closing (+60 EXP)` 
                  : 'Semua temuan di area Anda telah tuntas'}
              </p>
            </div>
          </div>

          <span className={`px-2.5 py-1 rounded-full text-[10.5px] font-black shrink-0 border ${
            openFindingsCount > 0 
              ? 'bg-rose-500 text-white border-rose-600 shadow-2xs' 
              : 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30'
          }`}>
            {openFindingsCount > 0 ? `${openFindingsCount} Open` : '✓ Selesai'}
          </span>
        </button>
      )}

      {/* ── SECTION: TUGAS TAMBAHAN & MODUL CEPAT ── */}
      <div className="space-y-2">
        <div className="flex items-center justify-between px-1">
          <h3 className="text-xs font-black uppercase tracking-wider text-[var(--text-muted)]">
            Modul Pendukung Lainnya
          </h3>
        </div>

        <div className="grid grid-cols-3 gap-2">
          {/* Pemantauan Lab (if lab) or Inspeksi Mingguan */}
          {isLaboratory ? (
            <button
              type="button"
              onClick={() => onNav('pemantauan')}
              className="flex flex-col items-center justify-center p-3 rounded-2xl border text-center transition-all active:scale-95 shadow-2xs hover:shadow-xs cursor-pointer"
              style={{
                backgroundColor: 'var(--card-bg, #FFFFFF)',
                borderColor: 'var(--border-main, #E2E8F0)'
              }}
            >
              <div className="w-8 h-8 rounded-xl bg-sky-500/10 text-sky-600 flex items-center justify-center mb-1.5">
                <ThermometerSun className="w-4 h-4" />
              </div>
              <span className="text-[10px] font-bold text-[var(--text-main)] leading-tight">
                Pemantauan Lab
              </span>
            </button>
          ) : (
            <button
              type="button"
              onClick={() => {
                setInspectionDefaultTab('weekly');
                setShowInspectionModal(true);
              }}
              className="flex flex-col items-center justify-center p-3 rounded-2xl border text-center transition-all active:scale-95 shadow-2xs hover:shadow-xs cursor-pointer"
              style={{
                backgroundColor: 'var(--card-bg, #FFFFFF)',
                borderColor: 'var(--border-main, #E2E8F0)'
              }}
            >
              <div className="w-8 h-8 rounded-xl bg-teal-500/10 text-teal-600 flex items-center justify-center mb-1.5">
                <ClipboardList className="w-4 h-4" />
              </div>
              <span className="text-[10px] font-bold text-[var(--text-main)] leading-tight">
                Inspeksi Mingguan
              </span>
            </button>
          )}

          {/* Sistem APD */}
          <button
            type="button"
            onClick={() => onNav('apd-input')}
            className="flex flex-col items-center justify-center p-3 rounded-2xl border text-center transition-all active:scale-95 shadow-2xs hover:shadow-xs cursor-pointer"
            style={{
              backgroundColor: 'var(--card-bg, #FFFFFF)',
              borderColor: 'var(--border-main, #E2E8F0)'
            }}
          >
            <div className="w-8 h-8 rounded-xl bg-orange-500/10 text-orange-600 flex items-center justify-center mb-1.5">
              <Shield className="w-4 h-4" />
            </div>
            <span className="text-[10px] font-bold text-[var(--text-main)] leading-tight">
              Sistem APD
            </span>
          </button>

          {/* Buletin K3 */}
          <button
            type="button"
            onClick={() => onNav('bulletin')}
            className="flex flex-col items-center justify-center p-3 rounded-2xl border text-center transition-all active:scale-95 shadow-2xs hover:shadow-xs cursor-pointer"
            style={{
              backgroundColor: 'var(--card-bg, #FFFFFF)',
              borderColor: 'var(--border-main, #E2E8F0)'
            }}
          >
            <div className="w-8 h-8 rounded-xl bg-indigo-500/10 text-indigo-600 flex items-center justify-center mb-1.5">
              <FileText className="w-4 h-4" />
            </div>
            <span className="text-[10px] font-bold text-[var(--text-main)] leading-tight">
              Buletin K3
            </span>
          </button>
        </div>
      </div>

      {/* ── SECTION: CHAT & HALL OF FAME ROW ── */}
      <div className="grid grid-cols-2 gap-2.5">
        <button
          type="button"
          onClick={() => window.dispatchEvent(new CustomEvent('open-chat-drawer'))}
          className="flex items-center gap-2.5 p-3 rounded-2xl border transition-all active:scale-95 shadow-2xs cursor-pointer"
          style={{
            backgroundColor: 'var(--card-bg, #FFFFFF)',
            borderColor: 'var(--border-main, #E2E8F0)'
          }}
        >
          <div className="w-8 h-8 rounded-xl bg-teal-500/15 text-teal-600 flex items-center justify-center shrink-0">
            <MessageSquare className="w-4 h-4" />
          </div>
          <div className="text-left min-w-0">
            <h4 className="text-xs font-bold text-[var(--text-main)] leading-tight truncate">
              Ruang Chat
            </h4>
            <span className="text-[9.5px] text-[var(--text-muted)] truncate block">
              Diskusi shift
            </span>
          </div>
        </button>

        <button
          type="button"
          onClick={() => onNav('leaderboard')}
          className="flex items-center gap-2.5 p-3 rounded-2xl border transition-all active:scale-95 shadow-2xs cursor-pointer"
          style={{
            backgroundColor: 'var(--card-bg, #FFFFFF)',
            borderColor: 'var(--border-main, #E2E8F0)'
          }}
        >
          <div className="w-8 h-8 rounded-xl bg-amber-500/15 text-amber-600 flex items-center justify-center shrink-0">
            <Trophy className="w-4 h-4" />
          </div>
          <div className="text-left min-w-0">
            <h4 className="text-xs font-bold text-[var(--text-main)] leading-tight truncate">
              Leaderboard
            </h4>
            <span className="text-[9.5px] text-[var(--text-muted)] truncate block">
              Peringkat EXP
            </span>
          </div>
        </button>
      </div>

      {/* ── BOTTOM BANNER: SWITCH TO FULL MODE ── */}
      <div 
        className="rounded-2xl p-3.5 border flex items-center justify-between gap-3 text-xs shadow-xs"
        style={{
          backgroundColor: 'var(--input-bg, #F8FAFC)',
          borderColor: 'var(--border-main, #E2E8F0)'
        }}
      >
        <div className="min-w-0">
          <p className="font-bold text-[11px] text-[var(--text-main)] flex items-center gap-1.5">
            <Smartphone className="w-3.5 h-3.5 text-teal-600" />
            <span>Mode Sederhana Aktif</span>
          </p>
          <p className="text-[10px] text-[var(--text-muted)] mt-0.5 line-clamp-1">
            Ingin melihat grafik analitik &amp; tabel lengkap?
          </p>
        </div>

        <button
          type="button"
          onClick={onSwitchToFullMode}
          className="px-3 py-1.5 rounded-xl bg-teal-600 hover:bg-teal-700 text-white font-bold text-xs shrink-0 transition-all active:scale-95 cursor-pointer shadow-xs flex items-center gap-1"
        >
          <span>Mode Lengkap</span>
          <ArrowRight className="w-3 h-3" />
        </button>
      </div>

      {/* Food Report Modal */}
      <FoodReportModal 
        isOpen={showFoodModal}
        onClose={() => setShowFoodModal(false)}
        userNik={inspectorNik}
        userName={inspectorName}
        userDept="ALL"
      />

      {/* Simplified Inspection & KTA/TTA Modal */}
      <SimplifiedInspectionModal
        isOpen={showInspectionModal}
        onClose={() => setShowInspectionModal(false)}
        inspectorNik={effectiveNik}
        inspectorName={effectiveName}
        userSection={effectiveSection}
        userJabatan={effectiveRole}
        schedule={mySchedule}
        defaultTab={inspectionDefaultTab}
        onNav={onNav}
        onSuccess={() => {
          // Refresh findings
          if (isPic) {
            fetch('/api/tickets')
              .then(r => r.ok ? r.json() : [])
              .then(tickets => {
                const matched = getOpenFindingsForSupervisor(effectiveRole, tickets);
                setOpenFindingsCount(matched.openFindings?.length || 0);
              })
              .catch(() => {});
          }
        }}
      />

      {/* Simplified P5M Schedule & Material Modal */}
      <SimplifiedP5mModal
        isOpen={showP5mModal}
        onClose={() => setShowP5mModal(false)}
        inspectorNik={inspectorNik}
        inspectorName={inspectorName}
        p5mAssignment={p5mAssignment}
        onNav={onNav}
      />

      {/* Community Quotes Pool Dialog Modal */}
      <QuotesPoolModal
        show={showQuotesPoolModal}
        onClose={() => setShowQuotesPoolModal(false)}
        selectedQuote={activeCommunityQuote}
        initialTab={quotesModalTab}
        onSelectAsDailyQuote={(q) => {
          setSelectedPoolQuote(q);
        }}
        inspectorNik={effectiveNik}
        inspectorName={effectiveName}
      />

      {/* Leadership Dashboard Modal (SPT Up) */}
      <LeadershipDashboardModal
        isOpen={showLeadershipModal}
        onClose={() => setShowLeadershipModal(false)}
        targetRole={leadershipTargetRole}
        inspectorName={effectiveName}
        inspectorNik={effectiveNik}
        onNav={onNav}
      />
    </motion.div>
  );
}
